#!/bin/bash
USER="dev"
NAME="UIUC Dev"
HOST="uiuc-vm"

#Usage
if [ "$#" != "2" ]; then
	echo "Usage: $0 <arch> <outfile>"
	exit 1
fi

# Parse Architecture
ARCH="$1"
if [[ "$ARCH" = "x86" || "$ARCH" = "32" ]]; then
	ARCH="i686"
elif [[ "$ARCH" = "amd64" || "$ARCH" = "64" ]]; then
	ARCH="x86_64"
elif [[ "$ARCH" != "x86_64" && "$ARCH" != "i686" ]]; then
	echo "Invalid Architecture $ARCH."
	exit 1
fi

# Must run as root
if [ "$(id -u)" -ne "0" ]; then
	echo "You must be running as root"
	exit 1
fi

# Install the required tools
PACMAN=$(which pacman 2>/dev/null)
if [ ! -x "$PACMAN" ]; then
	echo "Not on an archlinux system"
	exit 1
fi
PACKAGES="qemu-kvm virtualbox gptfdisk e2fsprogs arch-install-scripts"
$PACMAN -Sy --needed --noconfirm $PACKAGES
if [ "$?" -ne "0" ]; then
	echo "Failed to install base dependencies"
	exit 1
fi

# Force Cleanup
cleanup() {
	eval 'umount $DIR/boot 2>/dev/null'
	eval 'umount $DIR 2>/dev/null'
	eval 'loop_down "$LOOP" 2>/dev/null'
	eval 'qemu-nbd -d "$DEV" >/dev/null 2>&1'
	eval 'rm -f "$DISK"'
	eval 'rm -rf "$DIR"'
	exit $1
}
trap 'cleanup 1' INT QUIT

# Setup Temp
CONF="$(dirname "$(readlink -f "$0")")"
DIR="$(mktemp -d)"

# Create the virtual disk image
DISK="$2.vdi"
if [ -f "$DISK" ]; then
	rm -f "$DISK"
fi
qemu-img create -f qcow2 "$DISK" 100G

# Mount the Disk
modprobe nbd
FILES="$(ls /dev | grep nbd)"
for FILE in $FILES; do
	DEV="/dev/$FILE"
	qemu-nbd -n -c "$DEV" "$DISK" >/dev/null 2>&1
	if [ "$?" -eq "0" ]; then
		break
	fi
	DEV=""
done
if [ "$DEV" = "" ]; then
	echo "Failed to mount the virtual disk"
	cleanup 1
fi
read
cleanup 1

# Check for the virtual block device
if [ ! -b "$DEV" ]; then
	echo "Invalid Block Device!"
	cleanup 1
fi

# Setup Partition Table
sgdisk -z "$DEV"
sgdisk -o "$DEV"
sgdisk -n 1:2048:+1M "$DEV"
sgdisk -t 1:EF02 "$DEV"
sgdisk -n 2::+100M "$DEV"
sgdisk -n 3::+4G "$DEV"
sgdisk -n 4:: "$DEV"

BS="$(sudo gdisk -l "$DEV" | grep "Logical sector" | awk '{print $4}')"
offset() {
	echo $(expr $(sudo sgdisk "$DEV" -i "$1" | grep "First sector" | awk '{print $3}') \* $BS)
}
size() {
	echo $(expr $(sudo sgdisk "$DEV" -i "$1"| grep size | awk '{print $3}') \* $BS)
}
loop_up() {
	losetup -P -f --show "$DEV"
}
loop_down() {
	sleep 1
	losetup -d "$1"
}

# Format Disk
LOOP="$(loop_up)"
mkfs.ext2 -L boot "${LOOP}p2"
mkswap -L swap "${LOOP}p3"
mkfs.ext4 -L root "${LOOP}p4"

# Mount the disks
mount "${LOOP}p4" "$DIR"
mkdir "$DIR/boot"
mount "${LOOP}p2" "$DIR/boot"

# Setup Package List
BASE="bash bzip2 coreutils cronie dhcpcd diffutils e2fsprogs file filesystem findutils gawk gcc-libs gettext glibc grep gzip inetutils iproute2 iputils less licenses man-db man-pages nano netcfg pacman perl procps-ng psmisc sed shadow sysfsutils systemd systemd-sysvcompat tar texinfo usbutils util-linux vi which"
DEVEL="base-devel libpng gnuplot imagemagick gdb valgrind"
EDITORS="gvim emacs gedit"
NET="wget ntp subversion git ifplugd iptables"
SYS="sudo openssh lzop grub-bios zsh mlocate sshpass"
X11="xfce4 xfce4-goodies slim epdfview chromium firefox xorg-server xorg-xinit virtualbox-guest-modules virtualbox-guest-utils xf86-input-mouse xf86-input-keyboard gnome-themes-standard ttf-dejavu ttf-liberation"

# Run Pacman to Install Packages
pacstrap -c "$DIR" $BASE $DEVEL $EDITORS $NET $SYS $X11 --arch "$ARCH" --config "$CONF/sys/pacman.conf"
read
# Copy configuration
cp -r "$CONF/sys/etc" "$DIR"
cp -r "$CONF/sys/home" "$DIR/home/$USER"

# Setup Hostname
echo "$HOST" > "$DIR/etc/hostname"
echo "127.0.0.1 localhost localhost.uiuc" > "$DIR/etc/hosts"
echo "::1 localhost localhost.uiuc" > "$DIR/etc/hosts"

# Link Vi if replacing
#echo "ln -s /usr/bin/vim /usr/bin/vi" >> "$DIR/setup"

# Generate the Fstab
genfstab -U "$DIR" >> "$DIR/etc/fstab"

# Install Grub
echo "grub-install --boot-directory=/boot --recheck --no-floppy \"$DEV\"" >> "$DIR/setup"
echo "grub-mkconfig -o /boot/grub/grub.cfg" >> "$DIR/setup"

# Setup Locale
echo "locale-gen" >> "$DIR/setup"

# Build Initramfs
echo "mkinitcpio -p linux" >> "$DIR/setup"

# Setup Systemd Services
echo "systemctl enable cronie.service" >> "$DIR/setup"
echo "systemctl enable net-auto-wired.service" >> "$DIR/setup"
echo "systemctl enable ntpd.service" >> "$DIR/setup"
echo "systemctl enable slim.service" >> "$DIR/setup"
echo "systemctl enable sshd.service" >> "$DIR/setup"

# Setup Timezone
echo "ln -s /usr/share/zoneinfo/America/Chicago /etc/localtime" >> "$DIR/setup"

# Setup Sudoers
echo "echo \"%sudo ALL=(ALL) NOPASSWD: ALL\" >> /etc/sudoers" >> "$DIR/setup"

# Add Default User
echo "echo \"default_user $USER\" >> /etc/slim.conf" >> "$DIR/setup"
echo "groupadd sshaccess" >> "$DIR/setup"
echo "groupadd sudo" >> "$DIR/setup"
echo "useradd -s /bin/zsh -G sshaccess,sudo $USER" >> "$DIR/setup"
echo "chfn -f \"$NAME\" $USER" >> "$DIR/setup"
echo "chown -R $USER:users /home/$USER" >> "$DIR/setup"
REPO="$(git remote show -n origin | grep "Fetch URL" | awk '{print $3}')"
echo "su -c \"git clone \\\"$REPO\\\" /home/$USER/.vmtools\" $USER" >> "$DIR/setup"
echo "su -c \"/home/$USER/.vmtools/install-base\" $USER" >> "$DIR/setup"
echo "chmod -R +x /home/$USER/Desktop" >> "$DIR/setup"

# Run the Setup Script
arch-chroot "$DIR" "/bin/sh" "/setup"
shred "$DIR/setup"

rm "$DIR/setup"

# Cleanup
cleanup 0
