#!/bin/sh
DIR="${HOME}/.ssh"
#DIR="."
if [ ! -d "${DIR}" ]; then
	mkdir -p ${DIR}
fi
openssl genrsa -out ${DIR}/id_rsa 4096
chmod 0600 ${DIR}/id_rsa
echo `ssh-keygen -yf ${DIR}/id_rsa` `hostname` > ${DIR}/id_rsa.pub
openssl ecparam -genkey -name secp521r1 -out ${DIR}/id_ecdsa
chmod 0600 ${DIR}/id_ecdsa
echo `ssh-keygen -yf ${DIR}/id_ecdsa` `hostname` > ${DIR}/id_ecdsa.pub
exit 0
