#!/bin/sh
FILE=`readlink -f $0`
DIR=`dirname $FILE`

#UPDATE SUBMODULES IF THEY HAVEN'T BEEN
if [ "$1" != "1" ]; then
	"${DIR}/base/update-git2" 1
	exit 0
fi

#INSTALL CONFIGS
CONF="bash_profile bashrc zshrc zprofile"
for i in $CONF; do
	rm -f ~/.$i
	ln -sv ${DIR}/base/$i ~/.$i
	if [ ! -f ~/.$i.local ]; then
		if [ "$(echo $i | grep vim)" != "" ]; then
			echo "\"YOUR MODIFICATIONS HERE" > ~/.$i.local
		else
			echo "#YOUR MODIFICATIONS HERE" > ~/.$i.local
		fi
	fi
done

#INSTALL EMACS LOCAL CONF
if [ ! -f $HOME/.emacs.local ]; then
	touch $HOME/.emacs.local
fi

#INSTALL ZSH THEME FILE
if [ ! -f ~/.zsh.theme ]; then
	echo "ZSH_THEME=\"mh\"" > ~/.zsh.theme
fi

#DETERMINE IF PRELUDE CAN BE USED
EMACS="$(which emacs 2>/dev/null | grep -v "not found")"
if [ "$EMACS" != "" ]; then
	VER="$(${EMACS} --version | awk 'NR==1 {print $3}')"
	VER="$(printf "24.0\n%s" "$VER" | sort -bt. -k1,1n -k2,2n -k3,3n -k4,4n -k5,5n | awk 'NR==1')"
	if [ "$VER" = "24.0" ]; then
		#LINK PRELUDE
		rm -f "${HOME}/.emacs" "${DIR}/prelude/personal/emacs.el"
		rm -rf "${HOME}/.emacs.d"
		ln -sv "${DIR}/prelude" "${HOME}/.emacs.d"
		ln -sv "${DIR}/base/emacs_prelude" "${DIR}/prelude/personal/emacs.el"
	else
		rm -rf "${HOME}/.emacs.d"
		rm -f "${HOME}/.emacs"
		ln -sv "${DIR}/base/emacs" "${HOME}/.emacs"
	fi
fi
