#!/bin/bash
CONF="$(dirname "$(readlink -f "$0")")"

usage() {
	echo "Usage: $0 <course>"
}

currently_available() {
	echo "Currently Available Classes:"
	CLASSES="$(ls $CONF/setup_classes)"
	for i in $CLASSES; do
		echo -e "\t$i"
	done
}

#Validate Arguments
if [[ "$#" -eq "0" ]]; then
	currently_available
	exit 0
elif [[ "$#" -eq "1" && ! -f "$CONF/setup_classes/$1" ]]; then
	echo "Course $1 doesn't exist!"
	currently_available
	exit 1
elif [[ "$#" -ge "2" ]]; then
	usage
	exit 1
fi

echo "Preparing Environment for $1"
$CONF/setup_classes/$1
