#!/bin/bash
echo "Checking out your $2 folder..." >&2
if [ ! -d "$HOME/svn/cs225" ]; then
	subversion_checkout "cs225" "cs225" "0" >/dev/null
	if [ "$?" -ne "0" ]; then
		return $?
	fi
fi
if [ ! -d "$HOME/svn/cs225/monad" ]; then
	subversion_checkout "cs225/_shared/monad" "cs225/monad" "1" >/dev/null
	if [ "$?" -ne "0" ]; then
		return $?
	fi
fi
return 0
