#!/bin/bash
NAME="$(basename "$0")"
CONF="$(dirname "$(readlink -f "$0")")/.."
source "$CONF/base/scripts"
ARCH="$(get_arch)"

#Setup TMP Directory
TMP="$(mktemp -d)"

echo "Installing Packages..."
URL="https://comoto.cs.illinois.edu/cs225/class/cs233"
PKGS="iverilog-0.9.6-1 gtkwave-3.3.37-1"
cd $TMP
for i in $PKGS; do
	FILE="$i-$ARCH.pkg.tar.xz"
	wget "$URL/$FILE" >/dev/null 2>&1
	if [ "$?" -ne "0" ]; then
		echo "Failed to retrieve: $i" >&2
		rm -rf "$TMP"
		exit 1
	fi
	sudo pacman -U --noconfirm "$FILE" >/dev/null 2>&1
	if [ "$?" -ne "0" ]; then
		echo "Failed to install: $i" >&2
		rm -rf "$TMP"
		exit 1
	fi
done
cd $CONF

#Delete TMP Directory
rm -rf "$TMP"

#Don't checkout subversion twice
if [ ! -d "$HOME/svn/cs233" ]; then
	subversion_checkout "cs233" >/dev/null
	exit 0
fi
