#GET NEW CONFIG STUFF
$(dirname $(readlink -f ~/.bash_profile))/update-git

#OTHER STUFF
[[ -f ~/.bashrc ]] && . ~/.bashrc

#CUSTOM ENHANCEMENTS
if [ -f ~/.bash_profile.local ]; then
	. ~/.bash_profile.local
fi
