#!/bin/sh

get_arch() {
	echo "$(lscpu | grep Architecture | awk '{print $2}')"
}

get_netid() {
	echo "$(cat $HOME/.netid 2>/dev/null)"
}

get_year() {
	echo "$(date +%y)"
}

get_semester() {
	MONTH="$(date +%m)"
	DAY="$(date +%d)"
	SEM="su"
	if [ "$MONTH" -lt "5" ]; then
		SEM="sp"
	elif [ "$MONTH" -eq "5" ]; then
		if [ "$DAY" -lt "20" ]; then
			SEM="sp"
		fi
	elif [ "$MONTH" -ge "9" ]; then
		SEM="fa"
	elif [ "$MONTH" -eq "8" ]; then
		if [ "$DAY" -gt "14" ]; then
			SEM="fa"
		fi
	fi
	echo $SEM
}

NETID=
PASS=

test_netid() {
	DATA=$(curl -u "$USER:$PASS" "https://" 2>/dev/null)
	if [ "$(echo $DATA | grep "Authorization Required")" != "" ]; then
		return 1
	fi
	return 0
}

netid_prompt() {
	ERROR=1
	while [ "$ERROR" -gt "0" ]; do
		echo "" >&2
		echo -n "NETID: " >&2
		read NETID
		echo -n "AD Password: " >&2
		stty -echo
		read PASS
		stty echo
		echo "" >&2
		echo "" >&2
		DATA="$(curl -u "$NETID:$PASS" "https://subversion.ews.illinois.edu/svn/fa12-cs225/" 2>/dev/null)"
		if [ "$(echo "$DATA" | grep "Authorization Required")" != "" ]; then
			echo 'Invalid Username or Password!' >&2
		else
			ERROR=0
		fi
	done
	echo "$NETID" > "$HOME/.netid"
}

subversion_checkout() {
	ERROR=1000
	DIR="$HOME/svn/$2"
	if [ "$NETID" = "" ]; then
		NETID="$(get_netid)"
	fi
	while [ "$ERROR" -gt "0" ]; do
		if [ "$NETID" = "" ]; then
			RET="1"
			RES="authorization failed"
		else
			URL="https://subversion.ews.illinois.edu/svn/$(get_semester)$(get_year)-$1/$NETID"
			if [ "$3" = "1" ]; then
				URL="https://subversion.ews.illinois.edu/svn/$(get_semester)$(get_year)-$1"
			fi
			if [ "$PASS" = "" ]; then
				RES="$(svn co --non-interactive "$URL" "$DIR" </dev/null 2>&1)"
			else
				RES="$(svn co --non-interactive --username "$NETID" --password "$PASS" "$URL" "$DIR" </dev/null 2>&1)"
			fi
			RET="$?"
		fi
		ERROR=0
		if [ "$RET" != "0" ]; then
			if [ "$(echo "$RES" | grep "authorization failed")" != "" ]; then
				if [ "$PASS" != "" ]; then
					echo 'Invalid Username or Password!' >&2
				fi
				netid_prompt
				ERROR=999
			elif [ "$(echo "$RES" | grep "Could not resolve hostname")" != "" ]; then
				echo -n 'Could not connect to EWS, Try Again? (Y/n) ' >&2
				read AGAIN
				if [[ "$AGAIN" = "n" || "$AGAIN" = "N" ]]; then
					return 1
				fi
				echo "" >&2
				ERROR=999
			elif [ "$(echo "$RES" | grep "forbidden")" != "" ]; then
				echo 'Access Forbidden' >&2
				echo 'Are you sure you are enrolled in this class?' >&2
				return 1
			else
				echo 'An unknown SVN error has occurred!' >&2
				return 1
			fi
		fi
	done
	echo "Checked out the subversion folder for ${NETID} into ~/svn/$1" >&2
	return 0
}

setup_usage() {
	echo "Usage: $0 <course>"
}

setup_currently_available() {
	echo "Currently Available Classes:"
	CLASSES="$(ls $CONF/setup_classes)"
	for i in $CLASSES; do
		echo -e "\t$i"
	done
}

setup() {
	#Validate Arguments
	if [[ "$#" -eq "0" ]]; then
		setup_currently_available
		return 0
	elif [[ "$#" -eq "1" && ! -f "$CONF/setup_classes/$1" ]]; then
		echo "Course $1 doesn't exist!"
		setup_currently_available
		return 1
	elif [[ "$#" -ge "2" ]]; then
		setup_usage
		return 1
	fi

	echo "Preparing Environment for $1"
	source $CONF/setup_classes/$1
}

initialize_vm() {
	echo "" >&2
	echo "Virtual Environment Setup" >&2

	#SETUP SUBVERSION
	if [ ! -d $HOME/svn ]; then
		mkdir $HOME/svn
	fi
	rm -rf $HOME/.subversion
	mkdir $HOME/.subversion
	cat $CONF/base/subversion_servers | grep -v "store-plaintext-passwords" > $HOME/.subversion/servers

	netid_prompt
	
	#ASK ABOUT PLAINTEXT PASSWORDS
	while true; do
		echo -n "Would you like to store this password encrypted? (y/N) "
		read ENC
		if [ "$ENC" = "y" ]; then
			ENC="Y"
		fi
		if [ "$ENC" = "Y" ]; then
			echo "Installing Keyring..." >&2
			pacman -Q gnome-keyring >/dev/null 2>&1
			if [ "$?" -ne "0" ]; then
				get_packages "global" "gcr-3.6.2-2 libcap-ng-0.7.3-1 gnome-keyring-3.6.2-1"
				if [ "$?" -ne "0" ]; then
					continue
				fi
			fi
			pacman -Q libgnome-keyring >/dev/null 2>&1
			if [ "$?" -ne "0" ]; then
				get_packages "global" "libgnome-keyring-3.6.0-1"
				if [ "$?" -ne "0" ]; then
					continue
				fi
			fi
			if [ ! -d "$HOME/.gnome2" ]; then
				mkdir "$HOME/.gnome2"
			fi
			if [ ! -d "$HOME/.gnome2/keyrings" ]; then
				mkdir "$HOME/.gnome2/keyrings"
			fi
		else
			echo "store-plaintext-passwords = yes" >> $HOME/.subversion/servers
		fi
		break
	done

	#SETUP SSH
	if [ ! -f ~/.ssh/id_rsa ]; then
		${CONF}/install-ssh-keys >/dev/null 2>&1
	fi

	#ASK TO ADD SSH KEY TO EWS FOR EASY ACCESS
	echo -n "Would you like to add ssh keys to EWS for easy access from this vm? (y/N) " >&2
	read KEYS
	if [ "$KEYS" = "y" ]; then
		KEYS="Y"
	fi
	if [ "$KEYS" = "Y" ]; then
		ERROR=1
		while [ "$ERROR" -gt "0" ]; do
			sshpass -p "$PASS" ssh -o StrictHostKeyChecking=no "${NETID}@remlnx.ews.illinois.edu" "if [ ! -d ~/.ssh ]; then mkdir ~/.ssh; fi; echo \"$(cat ~/.ssh/id_rsa.pub)\" >> ~/.ssh/authorized_keys;" >/dev/null 2>&1
			if [ "$?" = "0" ]; then
				echo "Added SSH Keys Successfully" >&2
				echo "Type the command \`ews\` to access an ews ssh session" >&2
				ERROR=0
			else
				echo -n "Failed to set public key, Try Again? (Y/n) " >&2
				read TRY
				if [ "$TRY" = "n" ]; then
					ERROR=0
				fi
				if [ "$TRY" = "N" ]; then
					ERROR=0
				fi
			fi
		done
	fi

	#Ask About Courses
	echo "" >&2
	setup
	while [ "0" -eq "0" ]; do
		echo "" >&2
		echo -n "Select a course to install, to finish leave the field blank: " >&2
		read COURSE
		if [ "$COURSE" = "" ]; then
			break
		fi
		setup "$COURSE"
	done
	echo "If you would like to setup courses in the future" >&2
	echo "Use the command: setup <coursename>" >&2

	unset PASS
}

get_packages() {
	TMP="$(mktemp -d)"
	OLD="$(pwd)"
	cd $TMP
	URL="https://comoto.cs.illinois.edu/cs225/class/$1"
	PKGS="$2"
	ARCH="$(get_arch)"
	for i in $PKGS; do
		FILE="$i-$ARCH.pkg.tar.xz"
		wget "$URL/$FILE" >/dev/null 2>&1
		if [ "$?" -ne "0" ]; then
			echo "Failed to retrieve: $i" >&2
			cd "$OLD"
			rm -rf "$TMP"
			return 1
		fi
		sudo pacman -U --noconfirm "$FILE" >/dev/null 2>&1
		if [ "$?" -ne "0" ]; then
			echo "Failed to install: $i" >&2
			cd "$OLD"
			rm -rf "$TMP"
			return 1
		fi
	done
	cd "$OLD"
	rm -rf "$TMP"
}
