#!/bin/sh

get_netid() {
	echo "$(cat $HOME/.netid 2>/dev/null)"
}

get_year() {
	echo "$(date +%y)"
}

get_semester() {
	MONTH="$(date +%m)"
	DAY="$(date +%d)"
	SEM="su"
	if [ "$MONTH" -lt "5" ]; then
		SEM="sp"
	elif [ "$MONTH" -eq "5" ]; then
		if [ "$DAY" -lt "20" ]; then
			SEM="sp"
		fi
	elif [ "$MONTH" -ge "9" ]; then
		SEM="fa"
	elif [ "$MONTH" -eq "8" ]; then
		if [ "$DAY" -gt "14" ]; then
			SEM="fa"
		fi
	fi
	echo $SEM
}

subversion_checkout() {
	echo "Checking out your $1 folder..." >&2
	ERROR=1000
	DIR="$HOME/svn/$1"
	NETID="$(get_netid)"
	while [ "$ERROR" -gt "0" ]; do
		if [ "$NETID" = "" ]; then
			RET="1"
			RES="authorization failed"
		else
			URL="https://subversion.ews.illinois.edu/svn/$(get_semester)$(get_year)-$1/$NETID"
			if [ "$PASS" = "" ]; then
				RES="$(svn co "$URL" "$DIR" </dev/null 2>&1)"
			else
				RES="$(svn co --username "$NETID" --password "$PASS" "$URL" "$DIR" </dev/null 2>&1)"
			fi
			RET="$?"
		fi
		ERROR=0
		if [ "$RET" != "0" ]; then
			if [ "$(echo "$RES" | grep "authorization failed")" != "" ]; then
				if [ "$PASS" != "" ]; then
					echo 'Invalid Username or Password!' >&2
				fi
				echo ""
				echo -n "NETID: " >&2
				read NETID
				echo -n "AD Password: " >&2
				stty -echo
				read PASS
				stty echo
				echo "" >&2
				echo "" >&2
				ERROR=999
			elif [ "$(echo "$RES" | grep "Could not resolve hostname")" != "" ]; then
				echo -n 'Could not connect to EWS, Try Again? (Y/n) ' >&2
				read AGAIN
				if [[ "$AGAIN" = "n" || "$AGAIN" = "N" ]]; then
					return 1
				fi
				echo "" >&2
				ERROR=999
			else
				echo 'An unknown SVN error has occurred!' >&2
				echo 'Are you sure you are enrolled in this class?' >&2
				echo 'Please hit enter to continue...' >&2
				stty -echo
				read
				stty echo
				unset PASS
				return 1
			fi
		fi
	done
	echo "Checked out the subversion folder for ${NETID} into ~/svn/$1" >&2
	echo "$NETID" > "$HOME/.netid"
	echo $PASS
	unset PASS
	return 0
}

initialize_vm() {
	echo "CS 225 Virtual Environment Setup" >&2

	#SETUP SUBVERSION
	if [ ! -d $HOME/svn ]; then
		mkdir $HOME/svn
	fi
	rm -rf $HOME/.subversion
	mkdir $HOME/.subversion
	cp $CONF/base/subversion_servers $HOME/.subversion/servers
	cat $HOME/.subversion/servers | grep -v "store-plaintext-passwords" > $HOME/.subversion/servers
	echo "store-plaintext-passwords = yes" >> $HOME/.subversion/servers

	PASS="$(subversion_checkout "cs225")"
	if [ "$?" -ne "0" ]; then
		exit 1
	fi
	NETID="$(get_netid)"

	#SETUP SSH
	if [ ! -f ~/.ssh/id_rsa ]; then
		echo "Creating SSH Keys" >&2
		${CONF}/install-ssh-keys >/dev/null 2>&1
	fi

	#ASK TO ADD SSH KEY TO EWS FOR EASY ACCESS
	echo -n "Would you like to add ssh keys to EWS for easy access from this vm? (y/N) " >&2
	read KEYS
	if [ "$KEYS" = "y" ]; then
		KEYS="Y"
	fi
	if [ "$KEYS" = "Y" ]; then
		ERROR=1
		while [ "$ERROR" -gt "0" ]; do
			sshpass -p "$PASS" ssh -o StrictHostKeyChecking=no "${NETID}@remlnx.ews.illinois.edu" "if [ ! -d ~/.ssh ]; then mkdir ~/.ssh; fi; echo \"$(cat ~/.ssh/id_rsa.pub)\" >> ~/.ssh/authorized_keys;"
			if [ "$?" = "0" ]; then
				echo "Added SSH Keys Successfully" >&2
				echo "Type the command \`ews\` to access an ews ssh session" >&2
				ERROR=0
			else
				echo "Failed to set public key, Try Again? (Y/n)" >&2
				read TRY
				if [ "$TRY" = "n" ]; then
					ERROR=0
				fi
				if [ "$TRY" = "N" ]; then
					ERROR=0
				fi
			fi
		done
	fi
}
