#!/bin/sh
if [ ! -f "/etc/localtime" ]; then
	sudo ln -s "/usr/share/zoneinfo/America/Chicago" "/etc/localtime"
fi
if [ ! -f "/etc/hostname" ]; then
	echo "cs225-vm" | sudo tee "/etc/hostname" >/dev/null
fi
