# Path to your oh-my-zsh configuration.
export CONF="$(readlink -f $(dirname $(readlink -f ~/.zshrc))/../)"
ZSH="$CONF/oh-my-zsh"
echo "Checking For Updates..."
$CONF/base/update-git >/dev/null 2>&1
echo "Done."

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
. $HOME/.zsh.theme
if [ "$ZSH_THEME" = "" ]; then
	ZSH_THEME="mh"
fi

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git archlinux svn screen extract encode64)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
if [ ! -f "$HOME/.netid" ]; then
	echo "Initializing scripts. This may take some time..."
fi
source $CONF/base/useful
alias sudo="nocorrect sudo"

#Fix Things
$CONF/base/vmfixes

#CUSTOM ENHANCEMENTS
if [ -f ~/.zshrc.local ]; then
	. ~/.zshrc.local
fi

# Check for Setup Performed
if [ ! -f "$HOME/.netid" ]; then
	source $CONF/base/scripts
	initialize_vm
	return $?;
fi
