if [ ! -f "$HOME/.netid" ]; then
	echo "Initializing scripts. This may take some time..."
fi

if [ ! -f "/etc/localtime" ]; then
	sudo ln -s "/usr/share/zoneinfo/America/Chicago" "/etc/localtime"
fi

# Path to your oh-my-zsh configuration.
export CONF="$(readlink -f $(dirname $(readlink -f ~/.zshrc))/../)"
ZSH="$CONF/oh-my-zsh"
$CONF/base/update-git

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
. $HOME/.zsh.theme
if [ "$ZSH_THEME" = "" ]; then
	ZSH_THEME="mh"
fi

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git archlinux svn screen extract encode64)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
source $CONF/base/useful
alias sudo="nocorrect sudo"

#CUSTOM ENHANCEMENTS
if [ -f ~/.zshrc.local ]; then
	. ~/.zshrc.local
fi

# Check for Setup Performed
if [ -f "$HOME/.netid" ]; then
	return 0;
fi

echo "CS 225 Virtual Environment Setup"

#SETUP SUBVERSION
if [ ! -d $HOME/svn ]; then
	mkdir $HOME/svn
fi
rm -rf $HOME/.subversion
mkdir $HOME/.subversion
cp $CONF/base/subversion_servers $HOME/.subversion/servers
cat $HOME/.subversion/servers | grep -v "store-plaintext-passwords" > $HOME/.subversion/servers
echo "store-plaintext-passwords = yes" >> $HOME/.subversion/servers

source $CONF/base/scripts
PASS="$(subversion_checkout "cs225")"
NETID="$(get_netid)"
if [ "$?" -ne "0" ]; then
	exit 1
fi

#SETUP SSH
if [ ! -f ~/.ssh/id_rsa ]; then
	echo "Creating SSH Keys"
	${CONF}/install-ssh-keys >/dev/null 2>&1
fi

#ASK TO ADD SSH KEY TO EWS FOR EASY ACCESS
echo -n "Would you like to add ssh keys to EWS for easy access from this vm? (y/N) "
read KEYS
if [[ "$KEYS" = "y" || "$KEYS" = "Y" ]]; then
	ERROR=1
	while [ "$ERROR" > 0 ]; do
		sshpass -p "$PASS" ssh -o StrictHostKeyChecking=no "${NETID}@remlnx.ews.illinois.edu" "if [ ! -d ~/.ssh ]; then mkdir ~/.ssh; fi; echo \"$(cat ~/.ssh/id_rsa.pub)\" >> ~/.ssh/authorized_keys;"
	if [ "$?" = "0" ]; then
		echo "Added SSH Keys Successfully"
		echo "Type the command \`ews\` to access an ews ssh session"
		ERROR=0
	else
		echo "Failed to set public key, Try Again? (Y/n)"
		read TRY
		if [[ "$TRY" = "n" || "$TRY" = "N" ]]; then
			ERROR=0
		fi
	fi
fi
